version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
      - WEBUI_PORT=8080
    volumes:
      - /adresa...dokeri/qbit/appdata/config:/config
      - /adresa...dokeri/qbit/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
